// export const DOCUMENT_NAME = "syncedDocumentName"
// export const DOCUMENT_PAINT_STYLES = "syncedDocumentPaintStyles"
// export const DOCUMENT_TEXT_STYLES = "syncedDocumentTextStyles"
// export const DOCUMENT_ID = "syncedDocumentId"
// export const COLOR_SETTINGS = "colorSettings"
// export const TEXT_SETTINGS = "textSettings"
// export const OPENED_STATE = "openedState"
export const DB_VERSION = 'dbVersion'
export const SETTINGS = 'settings'
