export const DB_VERSION = 'pluginDbVersion'
export const SETTINGS = 'pluginSettings'
export const OPEN_STATE = 'pluginOpenState'
export const SYNCED_PAINT_STYLES = 'pluginSyncedPaintStyles'
export const SYNCED_TEXT_STYLES = 'pluginSyncedTextStyles'
export const LINTED_NODE_ID = 'pluginLintedNodeId'
