export const APP_START = "appStart"
export const APP_LINT = "appLint"
export const STYLES_EXPORT = "stylesExport"
export const STYLES_DELETE = "stylesDelete"
export const STYLES_UPDATE = "stylesUpdated"
export const COLOR_SETTINGS_CHANGE = "colorSettingsChange"
