export const DOCUMENT_NAME = "syncedDocumentName"
export const DOCUMENT_PAINT_STYLES = "syncedDocumentPaintStyles"
export const DOCUMENT_ID = "syncedDocumentId"
export const COLOR_SETTINGS = "colorSettings"
export const OPENED_STATE = "openedState"
