import './onRun'
import './onAppLint'
import './onSettingsUpdate'
import './onOpenStateUpdate'
import './onSelectionUpdate'
import './onSelectionChange'
import './onColorsImport'
import './onColorsDelete'
import './onTextsImport'
import './onTextsDelete'

// User Lint actions
import './onDeleteHidden'
import './onUngroupSingleGroups'
import './onMakePixelPerfect'
import './onMatchFillStyles'
import './onMatchTextStyles'
import './onNoGroups'